/**
 * Generate GLOSSARY_BRIEF.md — a prompt-ready file listing every glossary
 * term, its current state, and suggested backlinks. Hand the output to
 * Claude chat (or another LLM session) to author deep-dive content.
 *
 * Run with: npx tsx scripts/generate-glossary-brief.ts
 * Writes to: content-guides/GLOSSARY_BRIEF.md
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  ALPHABET,
  TAG_LABELS,
  TERMS,
  totalTerms,
  type Term,
} from '../src/app/glossary/data';

const PILLAR_BY_TAG: Record<string, string[]> = {
  auto: ['/auto-insurance', '/blog/ontario-auto-reform-2026-guide'],
  home: ['/home-insurance'],
  life: ['/life-insurance'],
  cc: ['/credit-cards', '/credit-cards/methodology'],
  legal: [],
};

function hasDeepDive(t: Term): boolean {
  return !!t.deepDive?.sections?.length;
}

function priority(t: Term): 'HIGH' | 'MEDIUM' | 'LOW' {
  // Reform-relevant or core auto/life concepts that get heavy search
  const HIGH = new Set([
    'opcf-13c', 'opcf-16', 'opcf-17', 'opcf-19', 'opcf-20', 'opcf-28a',
    'opcf-38', 'opcf-39', 'opcf-40', 'opcf-43', 'opcf-45', 'opcf-47', 'opcf-48',
    'catastrophic-impairment', 'minor-injury-guideline', 'income-replacement-benefit',
    'attendant-care-benefit', 'tort-claim', 'lat', 'first-party-benefits',
    'term-life-insurance', 'rider', 'mortgage-insurance',
    'collision-coverage', 'comprehensive-coverage', 'replacement-cost',
    'bundling', 'telematics',
  ]);
  const LOW = new Set([
    'claim', 'premium', 'cash-back', 'adjuster', 'binder',
  ]);
  if (HIGH.has(t.slug)) return 'HIGH';
  if (LOW.has(t.slug)) return 'LOW';
  return 'MEDIUM';
}

function suggestedBacklinksTo(t: Term): string[] {
  const out = new Set<string>();
  for (const tag of t.tags) {
    for (const url of PILLAR_BY_TAG[tag] ?? []) out.add(url);
  }
  // Heuristic cross-glossary suggestions: scan the definition for known
  // term names and propose links.
  const allSlugs = Object.values(TERMS).flat();
  const lowerDef = `${t.def} ${t.extra?.whyItMatters ?? ''}`.toLowerCase();
  for (const candidate of allSlugs) {
    if (candidate.slug === t.slug) continue;
    const name = candidate.name.toLowerCase();
    // Match on the bare keyword (drop parentheticals)
    const bare = name.replace(/\s*\(.+?\)\s*/g, '').trim();
    if (bare.length < 4) continue;
    if (lowerDef.includes(bare)) {
      out.add(`/glossary/${candidate.slug}`);
    }
  }
  return [...out].slice(0, 6);
}

function renderTerm(t: Term): string {
  const tags = t.tags.map((tg) => TAG_LABELS[tg]).join(', ');
  const deep = hasDeepDive(t) ? '✅ Has deep-dive' : '✗ STUB (needs deep-dive)';
  const prio = priority(t);
  const backlinks = suggestedBacklinksTo(t);
  const related = t.deepDive?.relatedTermSlugs ?? [];

  let out = `\n### ${t.name}\n`;
  out += `- **URL:** \`/glossary/${t.slug}\`\n`;
  out += `- **Tags:** ${tags}\n`;
  out += `- **Status:** ${deep} · **Priority:** ${prio}\n`;
  out += `- **Current definition:** ${t.def}\n`;
  if (t.extra?.whyItMatters) {
    out += `- **Existing "Why it matters" note:** ${t.extra.whyItMatters}\n`;
  }
  if (t.source) {
    out += `- **Existing source citation:** [${t.source.label}](${t.source.url})\n`;
  }
  if (backlinks.length > 0) {
    out += `- **Suggested internal backlinks (link TO these from the new deep-dive):**\n`;
    for (const b of backlinks) out += `  - \`${b}\`\n`;
  }
  if (related.length > 0) {
    out += `- **Already cross-linked in deep-dive related-terms sidebar:** ${related.map((s) => `\`/glossary/${s}\``).join(', ')}\n`;
  }
  return out;
}

function generateBrief(): string {
  const total = totalTerms(TERMS);
  const stubs = Object.values(TERMS).flat().filter((t) => !hasDeepDive(t));
  const deepDives = Object.values(TERMS).flat().filter(hasDeepDive);

  let out = `# TopRates.ca Glossary Deep-Dive Brief\n\n`;
  out += `> Auto-generated by \`scripts/generate-glossary-brief.ts\`. Re-run when \`src/app/glossary/data.ts\` changes.\n\n`;
  out += `**Total glossary terms:** ${total}\n`;
  out += `**With authored deep-dives:** ${deepDives.length}\n`;
  out += `**Stubs that need deep-dives:** ${stubs.length}\n\n`;

  out += `---\n\n`;
  out += `## For Claude (or whoever is writing deep-dives)\n\n`;
  out += `### What you're producing\n\n`;
  out += `For each glossary term marked as a STUB, write a deep-dive in the TypeScript shape used in \`src/app/glossary/data.ts\`. The shape:\n\n`;
  out += '```ts\n';
  out += `interface DeepDive {\n`;
  out += `  tagline?: string;                        // one-line framing under the H1\n`;
  out += `  sections: Array<{\n`;
  out += `    heading: string;                       // section H2\n`;
  out += `    paragraphs: string[];                  // each string is one <p>\n`;
  out += `  }>;\n`;
  out += `  faqs?: Array<{ question: string; answer: string }>;\n`;
  out += `  sources?: Array<{ label: string; url: string }>;\n`;
  out += `  relatedTermSlugs?: string[];             // slugs of other glossary terms\n`;
  out += `  ctas?: Array<{ label: string; href: string; description?: string }>;\n`;
  out += `}\n`;
  out += '```\n\n';
  out += `**Target length per term:** 4–6 sections, ~150–250 words each. 2–4 FAQs. 1–3 sources. 3–6 related terms.\n\n`;

  out += `### Compliance rules — STRICT\n\n`;
  out += `- **No invented dollar amounts** in examples. Real regulatory caps are fine (e.g., "$3,500 minor-injury cap" with FSRA/SABS citation), but worked examples that say "Aisha's $4,200 physio bill" are not.\n`;
  out += `- **No specific carrier market-share percentages** (e.g., "Intact 21.4% market share"). Reference carriers generically if at all.\n`;
  out += `- **No "average savings of X%"** style unsubstantiated stats.\n`;
  out += `- **No operator licence numbers** (e.g., "RIBO #84211"). The general "RIBO" is fine.\n`;
  out += `- **Cite FSRA, RIBO, or Ontario e-Laws** for any regulatory claim. Secondary sources (law firm blogs, insurer marketing) are OK as supporting reading but should not be the only citation for a regulatory fact.\n`;
  out += `- **Hedge where you would be guessing.** If you don't know the exact figure, describe the structure ("a monthly cap that varies by injury severity") rather than invent one.\n\n`;

  out += `### Internal backlinks — what to link TO\n\n`;
  out += `Every deep-dive should link OUT to:\n`;
  out += `1. **The most relevant pillar page** (e.g., \`/auto-insurance\` for auto terms, \`/life-insurance\` for life terms).\n`;
  out += `2. **The 2026 reform pillar** \`/blog/ontario-auto-reform-2026-guide\` for any term touched by the July 1, 2026 reform.\n`;
  out += `3. **Related glossary terms** via \`relatedTermSlugs\` (renders as a sidebar on the sub-page).\n`;
  out += `4. **Authoritative primary sources** in \`sources\` (FSRA / RIBO / Ontario e-Laws preferred).\n\n`;
  out += `Suggested backlinks for each term are listed under "Suggested internal backlinks" below — they're heuristic, refine as needed.\n\n`;

  out += `### Two existing deep-dives to use as templates\n\n`;
  out += `- \`/glossary/deductible\` — consumer-focused, decision framework, no regulatory citations needed.\n`;
  out += `- \`/glossary/accident-benefits\` — regulatory-heavy, FSRA-cited, links to reform pillar.\n`;
  out += `- \`/glossary/opcf-47r\` — highest-stakes reform term; FSRA + RIBO sources, full priority-of-payment explainer.\n\n`;
  out += `Open \`src/app/glossary/data.ts\` to see the exact TypeScript these compile to.\n\n`;

  out += `---\n\n`;
  out += `## Priority order\n\n`;
  out += `Stubs are tagged **HIGH / MEDIUM / LOW**:\n\n`;
  out += `- **HIGH:** reform-touched terms, core auto coverages, technical OPCFs that get search volume.\n`;
  out += `- **MEDIUM:** standard coverage terms most consumers want explained.\n`;
  out += `- **LOW:** basic terms where the one-line definition already does most of the job (e.g., "Claim", "Premium").\n\n`;
  out += `Work HIGH → MEDIUM → LOW. Within each priority, work the letters in order.\n\n`;

  out += `---\n\n`;
  out += `## All terms\n`;

  for (const letter of ALPHABET) {
    const list = TERMS[letter];
    if (!list || list.length === 0) continue;
    out += `\n### Letter ${letter} (${list.length} ${list.length === 1 ? 'term' : 'terms'})\n`;
    for (const t of list) {
      out += renderTerm(t);
    }
  }

  out += `\n---\n\n`;
  out += `## Suggested output format from Claude chat\n\n`;
  out += `For each completed deep-dive, paste a code block that drops into \`data.ts\`:\n\n`;
  out += '```ts\n';
  out += `// Add to the existing entry for "Catastrophic impairment" (slug: catastrophic-impairment)\n`;
  out += `deepDive: {\n`;
  out += `  tagline: '...',\n`;
  out += `  sections: [\n`;
  out += `    { heading: '...', paragraphs: ['...', '...'] },\n`;
  out += `    // ...\n`;
  out += `  ],\n`;
  out += `  faqs: [\n`;
  out += `    { question: '...', answer: '...' },\n`;
  out += `  ],\n`;
  out += `  sources: [\n`;
  out += `    { label: '...', url: 'https://...' },\n`;
  out += `  ],\n`;
  out += `  relatedTermSlugs: ['...'],\n`;
  out += `  ctas: [\n`;
  out += `    { label: '...', href: '/auto-insurance', description: '...' },\n`;
  out += `  ],\n`;
  out += `},\n`;
  out += '```\n';

  return out;
}

const output = generateBrief();
const outDir = resolve(process.cwd(), 'content-guides');
mkdirSync(outDir, { recursive: true });
const outPath = resolve(outDir, 'GLOSSARY_BRIEF.md');
writeFileSync(outPath, output, 'utf8');
console.log(`Wrote ${outPath} (${output.length.toLocaleString()} chars)`);
